import { DATA_STORE_KEYS } from "./dataStoreKeys";

// ----------- STORE TYPES -----------
export const DATA_STORE_LOCAL_STORAGE_KEYS = [
  DATA_STORE_KEYS.USER_ID,
  DATA_STORE_KEYS.DEVICE_ID,
];

export const DATA_STORE_SESSION_STORAGE_KEYS = [
  DATA_STORE_KEYS.UTM_MEDIUM,
  DATA_STORE_KEYS.UTM_SOURCE,
  DATA_STORE_KEYS.IS_SESSION_INIT,
];

export const DATA_STORE_COOKIE_STORAGE_KEYS = [
  DATA_STORE_KEYS.GRC_CHALLENGE,
  DATA_STORE_KEYS.RECAPTCHA_STATUS,
  DATA_STORE_KEYS.GRC_ACTION,
  DATA_STORE_KEYS.GRC_TOKEN,
  DATA_STORE_KEYS.AUTH_TOKEN
];
